TEST_ADMIN_EMAIL = "admin@test.com"
TEST_ADMIN_FULL_NAME = "Admin User"
TEST_CURATOR_FULL_NAME = "Curator User"
TEST_STUDENT_FULL_NAME = "Student User"
TEST_PASSWORD = "Password123!"
TEST_GENDER = "male"
TEST_AGE = 30
