TEST_USER_EMAIL = "user@test.com"
TEST_USER_FULL_NAME = "Custom User"
TEST_UPDATED_USER_FULL_NAME = "Updated User"
TEST_GENDER = "male"
TEST_AGE = 30
TEST_PASSWORD = "Password123!"
TEST_WRONG_PASSWORD = "wrong"

TEST_ADMIN_EMAIL = "admin@test.com"
TEST_ADMIN_FULL_NAME = "Admin User"
TEST_CURATOR_EMAIL = "curator@test.com"
TEST_CURATOR_FULL_NAME = "Curator User"
TEST_UPDATED_CURATOR_FULL_NAME = "Updated Curator"
TEST_PASSWORD = "Password123!"
TEST_GENDER = "male"
TEST_AGE = 30

TEST_ADMIN_EMAIL = "admin@test.com"
TEST_ADMIN_FULL_NAME = "Admin User"
TEST_CURATOR_FULL_NAME = "Curator User"
TEST_STUDENT_FULL_NAME = "Student User"
TEST_PASSWORD = "Password123!"
TEST_GENDER = "male"
TEST_AGE = 30
