# Generated by Django 4.1.5 on 2023-01-21 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("group", "0001_initial")]

    operations = [migrations.RemoveField(model_name="group", name="number_students")]
